#server:
#  port: 8081
#
#spring:
#  jackson:
#    property-naming-strategy: SNAKE_CASE
#
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    generate-ddl: true
#    defer-datasource-initialization: true
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb

server:
  port: 8081

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=testDB;encrypt=false
    username: rch
    password: 1234

jwt:
  secret: AAAABBBBCCCCDDDDEEEEFFFFGGGG123!@#

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    org.springframework.security: DEBUG
